create liveness&readiness
alifsyahakbar/Belajar-REST-API pull request #4
Opened 2022-10-15 11:44 UTC by alifsyahakbar

# Description of change

-

# Server configuration required

-

# Test recommendations

-

2022-10-15 12:26 UTC, omadijaya requested changes

2022-10-15 12:26 UTC, omadijaya commented on .github/workflows/laravel.yml
> +periodSeconds: 15
1 Github workflow bukan `Kubernetes` jadi gak perlu install itu
2 format yml nya salah. spasi tab di format YML itu penting jadi g sembarangan

2022-10-15 12:26 UTC, omadijaya commented on routes/web.php
> +    }
getDatabaseName returnya `string`  jadi kalau check lebih besar dari 0 kurang pas sih, if ($check) aja cukup harusnya

2022-10-15 12:52 UTC, alifsyahakbar commented on .github/workflows/laravel.yml
> +periodSeconds: 15
jdi hapus aja yg livenessprobe kebawahny?

2022-10-15 12:52 UTC, alifsyahakbar commented on routes/web.php
> +    }
okee

2022-10-16 02:04 UTC, omadijaya approved these changes

2022-10-16 02:09 UTC, merged